package graph;

import org.antlr.v4.runtime.Token;
import autogenerated.CymbolParser;

import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Map;
import java.util.HashMap;
import java.util.TreeMap;

public class CallGraph {
	private Comparator<String> lexicographic = new Comparator<String>() {
		public int compare(String s1, String s2) {
			return -s1.compareTo(s2);
		}
	};
	
	private List<String> funcNames = new ArrayList<String>();
	private Map<String, Integer> argCounts = new HashMap<String, Integer>();
	private Map<String, String> funcTypes = new HashMap<String, String>();
	private Map<String, List<String>> funcCalls = new TreeMap<String, List<String>>(lexicographic);
	
	public List<String> getDeclaredFunctions() {
		return funcNames;
	}
	
	public String getTypeOfFunction(String funcName) {
		return funcTypes.get(funcName);
	}
	
	public Map<String, List<String>> getFunctionCalls() {
		return funcCalls;
	}
	
	public int argumentCountOfFunction(String funcName) {
		return argCounts.get(funcName);
	}
	
	private Integer argumentCount(CymbolParser.ParamTypeListContext args) {
		return new Integer(args.paramType().size());
	}
	
	public boolean declareToken(
			Token funcDecl, 
			CymbolParser.TypeContext type, 
			CymbolParser.ParamTypeListContext arguments
	) {
		String name = funcDecl.getText();
		if(!funcNames.contains(name)) {
			funcNames.add(name);
			funcTypes.put(name, type.getText());
			if(arguments != null) {
				argCounts.put(name, this.argumentCount(arguments));
			} else {
				argCounts.put(name, new Integer(0));
			}
			return true;
		} else {
			return false;
		}
	}
	
	public void assertFunctionCall(Token caller, Token callee) {
		String callerName = caller.getText();
		String calleeName = callee.getText();
		
		List<String> callees;
		if(!funcCalls.containsKey(callerName)) {
			callees = new ArrayList<String>();
		} else {
			callees = funcCalls.get(callerName);
		}
		
		if(!callees.contains(calleeName)) {
			callees.add(calleeName);
		} 
		
		funcCalls.put(callerName, callees);
	}
}
